const DB = {
  reading:{
    easy:[
      {q:"The following text is adapted from Ida B. Wells's 1970 autobiography A Crusade for Justice. Mr. Watts is a reference to George Frederic Watts, an English painter. \"[Manchester\’s] art galleries are so arranged that the name of every picture is plainly seen and one has no need of a catalogue to pick out the name and the artist. This is a convenience to the general public, which other art galleries, which shall be nameless, might copy to advantage. To her treasure of art Manchester has added Mr. Watts’ latest picture, the Good Samaritan. As used in the text, what does the word \“arranged\” most nearly mean?",opts:["Organized","Ranked","Scheduled","Discussed"],ans:0,exp:"Choice A is the best answer because as used in the text, “arranged” most nearly means “organized.” The text states that a welcome feature of Manchester’s art galleries (as opposed to others) is that the titles of the paintings are easy to see and that a catalogue is therefore unneeded while visitors browse the art galleries. This suggests that the paintings are displayed in a systematic, or organized, way."},
      {q:"Due to their often strange images, highly experimental syntax, and opaque subject matter, many of John Ashbery’s poems can be quite difficult to ______ and thus are the object of heated debate among scholars. Which choice completes the text with the most logical and precise word or phrase?",opts:["Delegate","Compose","Interpret","Renounce"],ans:2,exp:"Choice C is the best answer because it most logically completes the text’s discussion of John Ashbery’s poems. As used in this context, “interpret” would mean decipher the meaning of. The text indicates that Ashbery’s poems have many unusual features, that it’s difficult to tell what exactly the poems’ subject matter is, and that scholars strongly disagree about the poems. This context conveys the idea that it’s difficult to interpret Ashbery’s poems."},
      {q:"One challenge of generating electricity from ocean waves is that wave power isn’t _______: it varies in unpredictable ways that pose technological and planning problems for electricity generation. Which choice completes the text with the most logical and precise word or phrase?",opts:["Accidental","Confident","Expensive","Consistent"],ans:3,exp:"Choice D is the best answer because it most logically completes the text’s discussion of the challenge of generating electricity from ocean waves. In this context, “consistent” means steady or unchanging over time. The text introduces a challenge and then explains that wave power varies, or changes, unpredictably in ways that cause problems for electricity generation. This context conveys that the challenge being described is a lack of consistency."},
      {q:"Diego Velázquez was the leading artist in the court of King Philip IV of Spain during the seventeenth century, but his influence was hardly _______ Spain: realist and impressionist painters around the world employed his techniques and echoed elements of his style. Which choice completes the text with the most logical and precise word or phrase?",opts:["Derived from","Recognized","Confided to","Represses by"],ans:2,exp:"Choice C is the best answer because it most logically completes the text’s discussion of John Ashbery’s poems. As used in this context, “interpret” would mean decipher the meaning of. The text indicates that Ashbery’s poems have many unusual features, that it’s difficult to tell what exactly the poems’ subject matter is, and that scholars strongly disagree about the poems. This context conveys the idea that it’s difficult to interpret Ashbery’s poems."},
      {q:"In response to concerns that some recent financial crises were exacerbated by consumers misunderstanding risks associated with credit cards, loans, and other financial products, policymakers in many countries have instituted risk-disclosure requirements on sellers of those products. Enrique Seira et al. investigated a variety of risk-disclosure messages sent to thousands of credit card customers and found that the messages had only small and short-lived effects on behavior. Seira et al. asserted that such effects may nevertheless be worth pursuing, given the negligible cost of messaging. Which choice best describes the function of the underlined portion in the text as a whole?",opts:["It notes a factor that led Seira et al. to not dismiss risk-disclosure messaging altogether despite their evidence of its limited utility.","It acknowledges a type of risk-disclosure messaging that Seira et al. may not have fully accounted for in their study."," It describes a consideration that explains why Seira et al. recommended risk-disclosure messaging even though its effects may be small relative to its cost","It points out a circumstance that Seira et al. conceded may make risk-disclosure messaging more effective than their study suggests"],ans:0,exp:"Choice A is the best answer because it most accurately describes the function of  the underlined portion in the text as a whole. The text establishes that many countries have adopted risk-disclosure requirements for financial products due to concerns that consumers don’t understand the risks associated with the products. According to the text, Seira et al. found that the effects of such messaging on consumer behavior were small and temporary. The text then adds that the researchers assert that because the cost of the messaging is negligible, the approach may be worth doing even if the effects are limited. Thus, the underlined portion notes a factor—very low cost—that led the researchers to not completely dismiss risk-disclosure messaging despite their evidence of its limited utility."},  
      {q:"Utah is home to Pando, a colony of about 47,000 quaking aspen trees that all share a single root system. Pando is one of the largest single organisms by mass on Earth, but ecologists are worried that its growth is declining in part because of grazing by animals. The ecologists say that strong fences could prevent deer from eating young trees and help Pando start thriving again. According to the text, why are ecologists worried about Pando?",opts:["It isn’t growing at the same rate it used to.","It isn’t producing young trees anymore.","It can’t grow into new areas because it is blocked by fences","Its root system can’t support many more new trees."],ans:0,exp:"Choice A is the best answer because it presents an explanation that is directly stated in the text for why ecologists are worried about Pando. The text states that Pando is a colony of about 47,000 quaking aspen trees that represents one of the largest organisms on Earth. According to the text, ecologists are worried that Pando’s growth is declining, partly because animals are feeding on the trees. In other words, the ecologists are worried that Pando isn’t growing at the same rate it used to. "},
      {q:"The following text is adapted from Charles W. Chesnutt’s 1901 novel The Marrow of Tradition. Mrs. Ochiltree was a woman of strong individuality, whose comments upon her acquaintance[s], present or absent, were marked by a frankness at times no less than startling. This characteristic caused her to be more or less avoided. Mrs. Ochiltree was aware of this sentiment on the part of her acquaintance[s], and rather exulted in it. Based on the text, what is true about Mrs. Ochiltree’s acquaintances?",opts:["They try to refrain from discussing topics that would upset Mrs. Ochiltree","They are unable to spend as much time with Mrs. Ochiltree as she would like.","They are too preoccupied with their own concerns to speak with Mrs. Ochiltree","They are likely offended by what Mrs. Ochiltree has said about them"],ans:3,exp:"Choice D is the best answer because it presents a statement about Mrs.  Ochiltree’s acquaintances that is supported by the text. The text indicates that  Mrs. Ochiltree makes comments about her acquaintances that are frank, or direct  and blunt, and sometimes startling. It also states that because of this behavior,  the acquaintances tend to avoid Mrs. Ochiltree. Together, these details suggest that the acquaintances choose not to be around Mrs. Ochiltree because they are offended by the things she has said about them"},
      {q:"“Mrs. Spring Fragrance” is a 1912 short story by Sui Sin Far. In the story, Mrs. Spring Fragrance, a Chinese immigrant living in Seattle, is traveling in California. In letters to her husband and friend, she emonstrates her concern for what’s happening at her home in Seattle while she is away: _______ Which quotation from Mrs. Spring Fragrance’s letters most effectively illustrates the claim?",opts:["“My honorable cousin is preparing for the Fifth Moon Festival, and wishes me to compound for the occasion some American ‘fudge,’ for which delectable sweet, made by my clumsy hands, you have sometimes shown a slight prejudice.”","“Next week I accompany Ah Oi to the beauteous  town of San José. There will we be met by the on of the Illustrious Teacher.”","“Forget not to care for the cat, the birds, and the flowers. Do not eat too quickly nor fan too vigorously now that the weather is warming.”","“I am enjoying a most agreeable visit, and American friends, as also our own, strive enevolently for the accomplishment of my pleasure."],ans:2,exp:"Choice C is the best answer because it presents a quotation that illustrates the claim that Mrs. Spring Fragrance demonstrates concern for what’s happening at home while she’s in California. By giving reminders to “care for the cat, the birds, and the flowers,” “not eat too quickly,” and avoid engaging in strenuous activity in the heat, Mrs. Spring Fragrance shows that she’s thinking about what’s happening at home and wants to ensure everything is taken care of."},
      {q:"In the 1960s, Gloria Richardson led a movement to promote racial equality. Her involvement in this effort was inspired by her daughter, Donna Richardson. In 1961, Donna joined protests organized by the Student Nonviolent Coordinating Committee in Cambridge, Maryland. Following her daughter, Gloria joined these protests too. Gloria soon became the cochair of the Cambridge Nonviolent Action Committee. She was also the leader of what became known as the Cambridge movement. According to the text, what did Gloria Richardson lead?",opts:["The Cambridge movement","Her daughter Donna’s high school","Protests to support environmental protections","A new business in Cambridge, Maryland"],ans:0,exp:"Choice A is the best answer because it presents information about Gloria Richardson that is supported by the text. The text provides a number of details about Gloria’s involvement in efforts to promote racial equality, including that she was the leader of what became known as the Cambridge movement. "},
      {q:"Beginning in the 1950s, Navajo Nation legislator Annie Dodge Wauneka continuously worked to promote public health; this _______ effort involved traveling throughout the vast Navajo homeland and writing a medical dictionary for speakers of Diné bizaad, the Navajo language. Which choice completes the text with the most logical and precise word or phrase?",opts:["impartial","offhand","persistent","mandatory"],ans:2,exp:"Choice C is the best answer because it most logically completes the text’s discussion of Annie Dodge Wauneka’s work as a Navajo Nation legislator. As used in this context, “persistent” means existing continuously. The text states that Wauneka “continuously worked to promote public health,” traveling extensively and authoring a medical dictionary; this indicates that Wauneka’s effort was persistent."},
    ],
    hard:[
      {q:"Although science fiction was dominated mostly by white male authors when Octavia Butler, a Black woman, began writing, she did not view the genre as _______: Butler broke into the field with the publication of several short stories and her 1976 novel Patternmaster, and she later became the first science fiction writer to win a prestigious MacArthur Fellowship. Which choice completes the text with the most logical and precise word or phrase?",opts:["legitimate","impenetrable","compelling","indecipherable"],ans:1,exp:"Choice B is the best answer because it most logically completes the discussion of Octavia Butler’s career. In this context, “impenetrable” means impossible to enter. The text indicates that the field of science fiction was dominated by white males when Butler, a Black woman, started writing, but she published several science fiction short stories and a novel and later won a prestigious award; that is, Butler pursued science fiction writing and had success. This context suggests that Butler didn’t view the genre as impossible to enter. "},
      {q:"The following text is adapted from Cynthia Kadohata’s 2004 novel Kira-Kira. [Uncle Katsuhisa] was as loud as my father was quiet. Even when he wasn’t talking, he made a lot of noise, clearing his throat and sniffing and tapping his fingers. Which choice best describes the function of the underlined sentence?",opts:[" It lists the kinds of topics Uncle Katsuhisa enjoys discussing."," It suggests that Uncle Katsuhisa dislikes meeting new people."," It contrasts Uncle Katsuhisa with the narrator’s father."," It describes a conversation between the narrator and the narrator’s father."],ans:2,exp:"Choice C is the best answer because it most accurately describes how the underlined sentence functions in the text as a whole. The underlined sentence establishes a difference between Uncle Katsuhisa and the narrator’s father by describing Uncle Katsuhisa as “loud” and the narrator’s father as “quiet.” "},
      {q:"Wakako Yamauchi is best known for And the Soul Shall Dance, her 1977 play about a Japanese American family in Southern California. The play is based on a short story Yamauchi had published three years earlier. Adapting the story wasn’t easy. Theater relies on dialogue between characters, but the original story features little dialogue and instead describes its characters’ silent thoughts. To transform the story into a play, Yamauchi created situations where characters reveal their thoughts by speaking them aloud during conversations with each other. Which choice best describes the function of the underlined sentence in the text as a whole?",opts:["It offers information about how Yamauchi adapted her short story into a play.","It argues that Yamauchi’s play influenced later playwrights."," It explains why Yamauchi’s short story is better known than the play adaptation is.",""],ans:0,exp:"Choice A is the best answer because it best describes how the underlined sentence functions in the text as a whole. According to the text, it was hard for Yamauchi to adapt her short story into the play And the Soul Shall Dance because the story had included little dialogue, instead describing the characters’ silent thoughts. The underlined sentence offers information about how Yamauchi ultimately succeeded in adapting the story into a play: it explains that Yamauchi created situations where the characters of the play could reveal their internal thoughts while speaking with each other"},      
      {q:"Among social animals that care for their young, such as chickens, macaque monkeys, and humans, newborns appear to show an innate attraction to faces and face-like stimuli. Elisabetta Versace and her colleagues used an image of three black dots arranged in the shape of eyes and a nose or mouth to test whether this trait also occurs in Testudo tortoises, which live alone and do not engage in parental care. They found that tortoise hatchlings showed a significant preference for the image, suggesting that ______ Which choice most logically completes the text?",opts:["face-like stimuli are likely perceived as harmless by newborns of social species that practiceparental care but as threatening by newborns of solitary species without parental care.","researchers should not assume that an innate attraction to face-like stimuli is necessarily an adaptation related to social interaction or parental care","researchers can assume that the attraction to face-like stimuli that is seen in social species that practice parental care is learned rather than innate.","newly hatched Testudo tortoises show a stronger preference for face-like stimuli than adult Testudo tortoises do."],ans:1,exp:"Choice B is the best answer because it presents the conclusion that most logically follows from the text’s discussion of the study by Versace and colleagues. The text indicates that newborn animals of some species are attracted to faces and to stimuli that resemble faces. These species, the text says, share two characteristics: they’re social and they practice parental care, meaning that parents care for their young. The text goes on to describe Versace and colleagues’ experiment, which showed that Testudo tortoises, which aren’t social and don’t practice parental care, were attracted to a stimulus that resembles a face. Since Versace and colleagues have shown that a species that isn’t social and doesn’t practice parental care nevertheless has the innate characteristic of being attracted to face-like stimuli, it follows that this characteristic shouldn’t be assumed to be an adaptation related to social interaction or parental care. "},
      {q:"In the twentieth century, ethnographers made a concerted effort to collect Mexican American folklore, but they did not always agree about that folklore’s origins. Scholars such as Aurelio Espinosa claimed that Mexican American folklore derived largely from the folklore of Spain, which ruled Mexico and what is now the southwestern United States from the sixteenth to early nineteenth centuries. Scholars such as Américo Paredes, by contrast, argued that while some Spanish influence is undeniable, Mexican American folklore is mainly the product of the ongoing interactions of various cultures in Mexico and the United States. Which finding, if true, would most directly support Paredes’s argument?",opts:["The folklore that the ethnographers collected included several songs written in the form of a décima, a type of poem originating in late sixteenth-century Spain.","Much of the folklore that the ethnographers collected had similar elements from region to region","Most of the folklore that the ethnographers  collected was previously unknown to scholars.","Most of the folklore that the ethnographers collected consisted of corridos—ballads about history and social life—of a clearly recent origin. "],ans:3,exp:"Choice D is the best answer because it presents a finding that, if true, would  support Paredes’s argument about the origin of Mexican American folklore. The  text describes a disagreement among scholars about whether Mexican American  folklore mostly derived from the folklore of Spain (the view held by Espinosa and  others) or originated in Mexico and the United States through ongoing cultural  interactions there (the view held by Paredes and others). If Mexican American  folklore collected in the twentieth century mostly consists of ballads about  history and social life that originated recently, then that would support Paredes’s  argument by suggesting that the folklore mostly arose after Spanish rule ended in   the early nineteenth century and that the folklore reflects cultural interactions in  Mexico and the United States rather than traditions from Spain. "},  
      {q:"The following text is from Georgia Douglas Johnson’s 1922 poem “Benediction.” Go forth, my son, Winged by my heart’s desire! Great reaches, yet unknown, Await For your possession. I may not, if I would, Retrace the way with you,My pilgrimage is through, But life is calling you! Which choice best states the main purpose of the text?",opts:["To express hope that a child will have the same accomplishments as his parent did","To suggest that raising a child involves many struggles","To warn a child that he will face many challenges throughout his life","To encourage a child to embrace the experiences life will offer"],ans:3,exp:"Choice D is the best answer because it accurately states the text’s main purpose. The poem begins with the speaker urging a child to “go forth” with her encouragement (“my heart’s desire”). The speaker goes on to suggest that new experiences (“Great reaches, yet unknown”) lie ahead for the son that “life is calling” him to seek out. Thus, the main purpose is to encourage a child to embrace the experiences available to him in his life."},
      {q:"Nigerian American author Teju Cole’s ______ his two passions—photography and the written word—culminates in his 2017 book, Blind Spot, which evocatively combines his original photographs logical and precise word or phrase?",opts:[" indifference to","enthusiasm for","concern about","surprise at"],ans:1,exp:"Choice B is the best answer because it most logically completes the text’s from his travels with his poetic prose. Which choice completes the text with the most discussion of Cole’s book Blind Spot. In this context, “enthusiasm for” means excitement about. The text explains that Blind Spot consists of original photographs as well as poetic prose—two elements that correspond to Cole’s passions, identified in the text, for photography and the written word. This context suggests that Cole’s excitement about photography and writing led him to create a book that successfully combines the two mediums."},
      {q:"The following text is from Edith Wharton’s 1905 novel The House of Mirth. Lily Bart and a companion are walking through a park. Lily had no real intimacy with nature, but she had a passion for the appropriate and could be keenly sensitive to a scene which was the fitting background of her own sensations. The landscape outspread below her seemed an enlargement of her present mood, and she found something of herself in its calmness, its breadth, its long free reaches. On the nearer slopes the sugar-maples wavered like pyres of light; lower down was a massing of grey orchards, and here and there the lingering green of an oak-grove. Which choice best describes the function of the underlined sentence in the text as a whole?",opts:["It creates a detailed image of the physical setting of the scene","It establishes that a character is experiencing an internal conflict.","It makes an assertion that the next sentence then expands on.","It illustrates an idea that is introduced in the previous sentence."],ans:3,exp:"Choice D is the best answer because it best describes how the underlined sentence functions in the text as a whole. The first sentence of the text establishes that Lily can be “keenly sensitive to” scenes that serve as a “fitting background” for her feelings—that is, she’s very aware of when a setting seems to reflect her mood. The next sentence, which is underlined, then demonstrates this awareness: Lily views the landscape she’s in as a large-scale reflection of her current mood, identifying with elements such as its calmness. Thus, the function of the underlined sentence is to illustrate an idea introduced in the previous sentence"},
      {q:"Individual elephants and Arctic herbivores such as caribou tend to have fixed geographic ranges throughout their lifetimes, which had prompted some researchers to speculate that the Arctic woolly mammoth, an extinct elephantid, might have exhibited similar behavior. Mammoth tusks grew in sequential layers, incorporating ingested minerals and organics, and so each ivory stratum reflects the ratio of strontium isotopes (87Sr/86Sr) in the local environment; thus, the sequence of strata shows where the animal roamed during life. Recent analysis of the strontium ratios in the strata of one Arctic woolly mammoth tusk in relation to the geographic distribution of strontium ratios in the environment shows the animal’s range begin to expand as it reached sexual maturity, only to contract again in its final 1.5 years. Which choice best describes the function of the underlined statement in the text as a whole?",opts:["It discusses a characteristic shared by certain animals in order to explain why researchers raised a possibility that turned out not to be supported by data described later in the text","It illustrates a pattern of behavior among certain animals in order to present a theory about exceptions to that pattern that is weakened by a finding described later in the text.","It describes a similarity in the behavior of certain animals in order to show why a method described later in the text did not reveal whether another animal also showed that behavior","It introduces a trait shared by certain animals in order to contextualize a hypothesis about the origin of that trait that is advanced later in the text"],ans:0,exp:"Choice A is the best answer because it most accurately describes how the underlined statement functions in the text as a whole. The underlined statement mentions a category of animals that have a feature in common: they tend to have fixed geographic ranges throughout their lifetimes. The text then presents the speculation of some researchers that the Arctic woolly mammoth might also share this characteristic. However, an examination of the content of strontium in the strata (or layers) of a woolly mammoth tusk indicated that contrary to the researchers’ hypothesis, the mammoth had an expanding range in its environment that contracted in its last 1.5 years of life. Thus, the underlined statement discusses a characteristic shared by certain animals in order to explain why researchers raised a possibility that turned out not to be supported by data described later in the text."},
      {q:"Chimamanda Ngozi Adichie’s 2013 novel Americanah chronicles the divergent experiences of Ifemelu and Obinze, a young Nigerian couple, after high school. Ifemelu moves to the United States to attend a prestigious university. ______, Obinze travels to London, hoping to start a career there. However, frustrated with the lack of opportunities, he soon returns to Nigeria. Which choice completes the text with the most logical transition?",opts:["Meanwhile","Nevertheless","Secondly","In fact"],ans:0,exp:"Choice A is the best answer. “Meanwhile” logically signals that the action described in this sentence (Obinze’s move to London to pursue a career) is simultaneous with the action described in the previous sentence (Ifemelu’s move to the United States). The first sentence establishes that the actions take place around the same time, referring to the characters’ “divergent experiences” following high school. "},
      {q:"Some members of the US Supreme Court have resisted calls to televise the court’s oral arguments, concerned that the participants would be tempted to perform for the cameras (and thus lower the quality of the discourse). _______, the justices worry that most viewers would not even watch the full deliberations, only short clips that could be misinterpreted and mischaracterized. Which choice completes the text with the most logical transition?",opts:["However","Additionally","In comparison","For example"],ans:1,exp:"Choice B is the best answer. “Additionally” logically signals that the claim in this sentence—that some Supreme Court justices worry that viewers (of televised court arguments) would watch only short, misleading clips—adds to the information in the previous sentence. Specifically, the previous sentence indicates one concern raised by those opposed to televising the court’s oral arguments, and the claim that follows indicates a second, additional concern."},
      {q:"Text 1: When companies in the same industry propose merging with one another, they often claim that the merger will benefit consumers by increasing efficiency and therefore lowering prices. Economist Ying Fan investigated this notion in the context of the United States newspaper market. She modeled a hypothetical merger of Minneapolis-area newspapers and found that subscription prices would rise following a merger. Text 2: Economists Dario Focarelli and Fabio Panetta have argued that research on the effect of mergers on prices has focused excessively on short-term effects, which tend to be adverse for consumers. Using the case of consumer banking in Italy, they show that over the long term (several years, in their study), the efficiency gains realized by merged companies do result in economic benefits for consumers.  Based on the texts, how would Focarelli and Panetta (Text 2) most likely respond to Fan’s findings (Text 1)?",opts:["They would recommend that Fan compare the  near-term effect of a merger on subscription prices in the Minneapolis area with the effect of a  merger in another newspaper market.","They would argue that over the long term the expenses incurred by the merged newspaper company will also increase","They would encourage Fan to investigate whether the projected effect on subscription prices persists over an extended period","They would claim that mergers have a different effect on consumer prices in the newspaper industry than in most other industries."],ans:2,exp:"Choice C is the best answer because, based on the information presented in the texts, it represents how Focarelli and Panetta would most likely respond to Fan’s findings. Text 1 indicates that Fan found that a newspaper merger would result in a rise in subscription prices. This rise wouldn’t benefit customers, who would have to pay more for news after a merger. Text 2 presents Focarelli and Panetta’s argument that merger research tends to focus too much on what happens immediately after the merger. Text 2 goes on to describe their finding that mergers can be economically beneficial for consumers over the long term. This suggests that Focarelli and Panetta would encourage Fan to investigate the long-term effect of the hypothetical newspaper merger on subscription prices"},
    ]
  },
  math:{
    easy:[
      {q:"The lengths of two sides of a triangle are 4 centimeters and 6 centimeters. If the perimeter of the triangle is 18 centimeters, what is the length, in centimeters, of the third side of this triangle?",opts:["2","8","10","24"],ans:1,exp:"Choice B is correct. The perimeter of a triangle is the sum of the lengths of all three of its sides. It’s given that the lengths of two sides of a triangle are 4 centimeters and 6 centimeters. Let x represent the length, in centimeters, of the third side of this triangle. The sum of the lengths, in centimeters, of all three sides of the triangle can be represented by the expression 4 6 + +x. Since it’s given that the perimeter of the triangle is 18 centimeters, it follows that 4 6 + +x=18, or 10 18 + =x . Subtracting 10 from both sides of this equation yields x=8. Therefore, the length, in centimeters, of the third side of this triangle is 8"},       {q:"",opts:["","","",""],ans:2,exp:""},
      {q:"16x + 30 = 190 Which equation has the same solution as the given equation?",opts:["16x = 30","16x = 130","16x = 160","16x = 190"],ans:2,exp:"Choice C is correct. It’s given that 16 30 19 x+ = 0. Subtracting 30 from each side of this equation yields 16x = 160. Therefore, the equation 16x = 160 is equivalent to the given equation and has the same solution."},      
      {q:"Ty set a goal to walk at least 24 kilometers every day to prepare for a multiday hike. On a certain day, Ty plans to walk at an average speed of 4 kilometers per hour. What is the minimum number of hours Ty must walk on that day to fulfill the daily goal?",opts:["4","6","20","24"],ans:1,exp:"Choice B is correct. It’s given that Ty plans to walk at an average speed of 4 kilometers per hour. The number of kilometers Ty will walk is determined by the expression 4s, where s is the number of hours Ty walks. The given goal of at least 24 kilometers means that the inequality 4s>=24 represents the situation. Dividing both sides of this inequality by 4 gives s$6, which corresponds to a minimum of 6 hours Ty must walk."},
      {q:"The function g is defined by g(x) = x^2 + 9. For which value of x is g(x) = 25?",opts:["4","5","9","13"],ans:0,exp:"Choice A is correct. It’s given that g(x) = x^2 + 9. Substituting 25 for g(x) in this equation yields 25 = x^2 + 9. Subtracting 9 from both sides of this equation yields 16 = x^2. Taking the square root of each side of this equation yields x= +-4. It follows that g(x) = 25 when the value of x is 4 or -4. Only 4 is listed among the choices."},
      {q:"Which expression is equivalent to 9x^2 + 5x?",opts:["x(9x + 5)","5x(9x + 1)","9x(x + 5)","x^2(9x + 5)"],ans:0,exp:"Choice A is correct. Since x is a factor of each term in the given expression, the expression is equivalent to x(9x) + x(5) or x(9x+5)"},
      {q:"Each value in the data set shown represents the height, in centimeters, of a plant. 6, 10, 13, 2, 15, 22, 10, 4, 4, 4 What is the mean height of these plants?",opts:["8.8","8","7.6","9"],ans:3,exp:"Choice D is correct. The mean of a data set is the sum of the values in the data set divided by the number of values in the data set. It follows that the mean height of these plants is the sum of the heights of each plant, which is 90, divided by the number of plants in the data set, 10. Therefore, the mean height of these plants is 90/10, or 9."},
      {q:"Jay walks at a speed of 3 miles per hour and runs at a speed of 5 miles per hour. He walks for w hours and runs for r hours for a combined total of 14 miles. Which equation represents this situation?",opts:["3w + 5r = 14","1/3w + 1/5r = 14","1/3w + 1/5r = 112","3w + 5r = 122"],ans:0,exp:"Choice A is correct. Since Jay walks at a speed of 3 miles per hour for w hours, Jay walks a total of 3w miles. Since Jay runs at a speed of 5 miles per hour for r hours, Jay runs a total of 5r miles. Therefore, the total number of miles Jay travels can be represented by 3w + 5r. Since the combined total number of miles is 14, the equation 3w + 5r = 14 represents this situation"},
      {q:"John paid a total of $165 for a microscope by making a down payment of $37 plus p monthly payments of $16 each. Which of the following equations represents this situation?",opts:["16p - 37 = 165","37p - 16 = 165","16p + 37 = 165","37p + 16 = 165"],ans:2,exp:"Choice C is correct. It’s given that John made a $16 payment each month for p months. The total amount of these payments can be represented by the expression 16p. The down payment can be added to that amount to find the total amount John paid, yielding the expression 16p + 37. It’s given that John paid a total of $165. Therefore, the expression for the total amount John paid can be set equal to that amount, yielding the equation 16p + 37 = 165."},
      {q:"y - 57 = px The given equation relates the positive numbers p, x, and y. Which equation correctly expresses y in terms of p and x",opts:["y = 57x + p","y = pc + 57","y = 57px","y = px/57"],ans:1,exp:"Choice B is correct. Adding 57 to each side of the given equation yields y = px + 57. Therefore, the equation y = px + 57 correctly expresses y in terms of p and x."},
    ],
    hard:[
      {q:"4x - 9y = 9y + 5  hy = 2 + 4x In the given system of equations, h is a constant. If the system has no solution, what is the value of h",opts:["-9","0","9","18"],ans:3,exp:"Choice D is correct. A system of two linear equations in two variables, x and y, has no solution if the lines represented by the equations in the xy-plane are distinct and parallel. The graphs of two lines in the xy-plane represented by equations in the form Ax + By = CC, where A, B, and C are constants, are parallel if the coefficients for x and y in one equation are proportional to the corresponding coefficients in the other equation. The first equation in the given system can be written in the form Ax + By = C  by subtracting 9y from both sides of the equation to yield 4x - 18y = 5. The second equation in the given system can be written in the form Ax + By = c by subtracting 4x from both sides of the equation to yield -4x + hy = 2. The coefficient of x in this second equation, -4, is -1 times the coefficient of x in the first equation, 4. For the lines to be parallel, the coefficient of y in the second equation, h, must also be -1 times the coefficient of y in the first equation, -18. Thus,h = -1(-18), or h=18. Therefore, if the given system has no solution, the value of h is 18."},
      {q:"Function f is defined by f(x) = (x+6)(x + 5)(x + 1). Function g is defined by g(x) = f(x -1) The graph of y = g(x) in the xy-plane has x-intercepts at (a, 0), (b,0), and (c, 0) where a, b, and c are distinct constants. What is the value of a + b + c?",opts:["","","",""],ans:1,exp:"Choice B is correct. It's given that g(x = f(x - 1). Since f(x) = (x + 6)(x + 5)(x + 1), it follows that f(x - 1) = (x + 5)(x + 4)(x). Therefore g(x) = x(x + 5)(x + 4). The x-intercepts of a graph in the xy-plane are the points where y=0. The x-coordinates of the x-intercepts of the graph of y = g(x) in the xy-plane can be found by solving the equation 0 = x(x + 5)(x + 4). Applying the zero product property to this equation yilds three equations: x = 0, x + 5 = 0, and x + 4 = 0. Solving each of theses equations for x yeilds x = 0, x = -5, and x = -4 respectivly. Therefore the x-intercepts of the graph of y = g(x) are (0,0), (-5,0) and (-4,0). It follows that the valuses of a, b, and c are 0, -5, and - 4. Thus,  the value of a+b+c is ) + (-5) + (-4) which is equal to -9."},
      {q:"Right rectangular prism X is similar to right rectangular prism Y. The surface area of right rectangular prism X is 58 cm^2, and the surface area of right rectangular prism Y is 1,450 cm^2. The volume of right rectangular prism Y is 1,250 cm^3. What is the sum of the volumes, in cm^3, of right rectangular prism X and right rectangular prism Y?",opts:["1250","1260","1111","6767"],ans:2,exp:"The correct answer is Choice C. Since it’s given that prisms X and Y are similar, all the linear measurements of prism Y are k times the respective linear measurements of prism X, where k is a positive constant. Therefore, the surface area of prism Y is k^2 times the surface area of prism X and the volume of prism Y is k^3 times the volume of prism X. It’s given that the surface area of prism Y is 1450 cm^2 , and the surface area of prism X is 58 cm2 , which implies that 1450 = 58k^2. Dividing both sides of this equation by 58 yields1450/58 = k^2 or k^2 = 25.  Since k is a positive constant, k = 5. It’s given that the volume of prism Y is 1250 cm^3 . Therefore, the volume of prism X is equal to1250/k^3 cm^3 , which is equivalent to 10 cm^3 . Thus, the sum of the volumes, in cm3 , of the two prisms is 1260."},
      {q:"Angel Cruz: 483 Terry Smith: 320. The table shows the results of a poll. A total of 803 voters selected at random were asked which candidate they would vote for in the upcoming election. According to the poll, if 6,424 people vote in the election, by how many votes would Angel Cruz be expected to win?",opts:["163","1304","3864","5621"],ans:2,exp:"Choice B is correct. It’s given that 483 out of 803 voters responded that they would vote for Angel Cruz. Therefore, the proportion of voters from the poll who responded they would vote for Angel Cruz is 483/803. It’s also given that there are a total of 6424  voters in the election. Therefore, the total number of people who would be expected to vote for Angel Cruz is 6424(483/803) or 3864. Since 3864 of the 6424 total voters would be expected to vote for Angel Cruz, it follows that 2560 voters would be expected not to vote for Angel Cruz. The difference in the number of votes for and against Angel Cruz is 1304 votes. Therefore, if 6424 people vote in the election, Angel Cruz would be expected to win by 1304 votes"},
      {q:"The funciton f is defined by f(x) = 7x - 84. What is the x-intercept of the graph of y = f(x) in the xy-plane?",opts:["(-12,0)","(-7,0)","(7,0)","(12,0)"],ans:3,exp:"Choice D is correct. The given function f is a linear function. Therefore, the graph of y = f(x) in the xy-plane has one x-intercept at the point (k,0) where k is a constant. Substituting 0 for f(x) and k for x in the given function yields 0 = 7k - 84. Adding 84 to both sides of this equation yields 84 = 7k. Dividing both sides of this equation by 7 yields 12 = k. Therefore, the x-intercept of the graph of y = f(x)  in the xy-plane is (12,0)"},
      {q:"w(t) = 300 - 4t The function w models the volume of liquid, in milliliters, in a container t seconds after it begins draining from a hole at the bottom. According to the model, what is the predicted volume, in milliliters, draining from the container each second?",opts:["300","296","75","4"],ans:3,exp:"Choice D is correct. It’s given that the function w models the volume of liquid, in milliliters, in a container t seconds after it begins draining from a hole at the bottom. The given functions(t) = 300 - 4t can be rewritten as w(t) = - 4t + 300. Thus, for each increase of t by 1, the value of w(t) decreases by  4. Therefore, the predicted volume, in milliliters, draining from the container each second is 4 milliliters."},
      {q:"Triangle FGH is similar to triangle JKL , where angle F corresponds to angle J and angles G and K are right angles. If sin (F) =  308/317, what is the value of sin(J)?",opts:["75/317","308/317","317/308","317/75"],ans:1,exp:"Choice B is correct. If two triangles are similar, then their corresponding angles are congruent. It’s given that right triangle FGH is similar to right triangle JKL and angle F corresponds to angle J. It follows that angle F is congruent to angle J and, therefore, the measure of angle F is equal to the measure of angle J. The sine ratios of angles of equal measure are equal. Since the measure of angle F is equal to the measure of angle J, sin(F) = sin(J) . It’s given that sin Therefore, sin(J) is 308/317."},
      {q:"A square is inscribed in a circle. The radius of the circle is (20sqrt(2))/2 inches. What is the side length, in inches, of the square?",opts:["20"," (20sqrt(2))/2","20sqrt(2)","40"],ans:0,exp:"Choice A is correct. When a square is inscribed in a circle, a diagonal of the square is a diameter of the circle. It’s given that a square is inscribed in a circle and the length of a radius of the circle is  (20sqrt(2))/2 inches. Therefore, the length of a diameter of the circle is 20sqrt(2) inches. It follows that the length of a diagonal of the square is 20sqrt(2) inches. A diagonal of a square separates the square into two right triangles in which the legs are the sides of the square and the hypotenuse is a diagonal. Since a square has 4 congruent sides, each of these two right triangles has congruent legs and a hypotenuse of length 20sqrt(2) inches. Since each of these two right triangles has congruent legs, they are both 45-45-90 triangles. In a 45-45-90 triangle, the length of the hypotenuse is 2 times the length of a leg. Let s represent the length of a leg of one of these 45-45-90 triangles. It follows that 20sqrt(2)=sqrt(2)(s) . Dividing both sides of this equation by 2 yields20 = s. Therefore, the length of a leg of one of these 45-45-90 triangles is 20 inches. Since the legs of these two 45-45-90 triangles are the sides of the square, it follows that the side length of the square is 20 inches."},
      {q:"A certain town has an area of 4.36 square miles. What is the area, in square yards, of this town? (1 mile = 1,760 yards)",opts:["404","7674","710459","13505536"],ans:3,exp:"Choice D is correct. Since the number of yards in 1 mile is 1760, the number of square yards in 1 square mile is (1760)(1760) == 3097600. Therefore, if the area of the town is 4.36 square miles, it is4.36(3097600) = 13505536, in square yards"},
      {q:"Triangle XYZ is similar to triangle RST such that X, Y, and Z correspond to R, S, and T, respectively. The measure of ∠Z is 20° and 2XY = RS. What is the measure of ∠T ?",opts:["2°","10°","20°","40°"],ans:2,exp:"Choice C is correct. It’s given that triangle XYZ is similar to triangle RST, such that X, Y, and Z correspond to R, S, and T, respectively. Since corresponding angles of similar triangles are congruent, it follows that the measure of ∠Z is congruent to the measure of ∠T. It’s given that the measure of ∠Z is 20°. Therefore, the measure of ∠T is 20°."}
    ],
  }
};

const SUBJECTS = ["math","reading"];
const DIFF_PTS = {easy:10,hard:30};
const LABELS = {math:"Mathematics",reading:"Reading and English"};

let state = {
  subject:"reading", diff:"easy",
  qIdx:0,
  answers:{}, // key: "subj-diff-idx" -> {selected, correct}
  points:0, correct:0, incorrect:0,
  currentPlayer: 1, // 1 or 2
  gameMode: "single", // "single" or "multiplayer"
  players: {
    1: {name: "Player 1", wins: 0},
    2: {name: "Player 2", wins: 0}
  }
};

function getKey(idx){ return `${state.subject}-${state.diff}-${idx}`; }
function getQs(){ return DB[state.subject][state.diff]; }

function setSubject(s){
  state.subject=s; state.diff=document.getElementById("diffSel").value;
  state.qIdx=0; state.currentPlayer=1; render();
}

function changeSubject(){
  state.subject=document.getElementById("subjectSel").value;
  state.qIdx=0; state.currentPlayer=1; render();
}

function changeDiff(){
  state.diff=document.getElementById("diffSel").value;
  state.qIdx=0; state.currentPlayer=1; render();
}

function changeMode(){
  state.gameMode=document.getElementById("modeSel").value;
  state.qIdx=0; state.currentPlayer=1; render();
}

function render(){
  const qs = getQs();
  const q = qs[state.qIdx];
  const key = getKey(state.qIdx);
  const answered = state.answers[key];
  const subwaySurfers = document.getElementById("subwaySurfers");

  // Show/hide player indicator based on game mode
  const playerIndicator = document.getElementById("playerIndicator");
  playerIndicator.style.display = state.gameMode === "multiplayer" ? "flex" : "none";

  // Update current player display
  document.getElementById("player1Badge").classList.toggle("active", state.currentPlayer === 1);
  document.getElementById("player2Badge").classList.toggle("active", state.currentPlayer === 2);

  document.getElementById("qNum").textContent = `Q${state.qIdx+1}`;
  const diffEl = document.getElementById("qDiff");
  diffEl.textContent = state.diff.charAt(0).toUpperCase()+state.diff.slice(1);
  diffEl.className = `q-diff diff-${state.diff}`;
  document.getElementById("qText").textContent = q.q;

  const letters = ["A","B","C","D"];
  const optsEl = document.getElementById("opts");
  optsEl.innerHTML = q.opts.map((o,i)=>{
    let cls = "opt";
    if(answered!==undefined){
      cls+=" locked";
      if(i===q.ans) cls+=" correct";
      else if(i===answered.selected && answered.selected!==q.ans) cls+=" wrong";
    }
    return `<button class="${cls}" onclick="pick(${i})">
      <div class="opt-letter">${letters[i]}</div>
      <span>${o}</span>
    </button>`;
  }).join("");

  const fb = document.getElementById("feedback");
  const fbIcon = document.getElementById("fbIcon");
  const fbText = document.getElementById("fbText");
  if(answered!==undefined){
    fb.className = `feedback show ${answered.correct?'ok':'bad'}`;
    fbIcon.className = `icon ${answered.correct?'ok-i':'bad-i'}`;
    fbIcon.textContent = answered.correct?"✓":"✕";
    const nextPlayer = state.currentPlayer === 1 ? 2 : 1;
    if(state.gameMode === "multiplayer"){
      if(answered.correct){
        fbText.textContent = "Correct! "+q.exp;
        fbText.textContent += ` | Go place your piece on the board!`;
      } else {
        fbText.textContent = "Incorrect. "+q.exp;
        fbText.textContent += ` | ${state.players[nextPlayer].name}, get ready!`;
      }
    } else {
      fbText.textContent = answered.correct ? "Correct! "+q.exp : "Incorrect. "+q.exp;
    }
  } else {
    fb.className="feedback";
  }

  const done = Object.keys(state.answers).filter(k=>k.startsWith(`${state.subject}-${state.diff}-`)).length;
  const pct = Math.round((done/qs.length)*100);
  document.getElementById("progFill").style.width = pct+"%";
  document.getElementById("progLabel").textContent = `Question ${state.qIdx+1} of ${qs.length}`;
  document.getElementById("progPct").textContent = pct+"%";
  document.getElementById("pointsBadge").textContent = state.points+" pts";
  document.getElementById("correctCount").textContent = state.correct;
  document.getElementById("incorrectCount").textContent = state.incorrect;

  const skipped = qs.length - done - (answered!==undefined?0:0);
  document.getElementById("skippedCount").textContent = Math.max(0, qs.length - done);

  document.getElementById("prevBtn").disabled = state.qIdx===0;
  document.getElementById("nextBtn").textContent = state.qIdx===qs.length-1 ? "Finish" : "Next →";

  if (state.points >= 20) {
    subwaySurfers.style.display = "flex";
  }
  else {
    subwaySurfers.style.display = "none";
  }
}

function pick(i){
  const key = getKey(state.qIdx);
  if(state.answers[key]!==undefined) return;
  const qs = getQs();
  const correct = i===qs[state.qIdx].ans;
  state.answers[key] = {selected:i, correct};
  if(correct){ state.correct++; state.points+=DIFF_PTS[state.diff];music_player() }
  else { state.incorrect++; }
  render();
}

function navigate(dir){
  const qs = getQs();
  const key = getKey(state.qIdx);
  const answered = state.answers[key];
  
  // Switch players when moving forward to the next question (only in multiplayer mode)
  if(dir === 1 && answered && state.gameMode === "multiplayer"){
    state.currentPlayer = state.currentPlayer === 1 ? 2 : 1;
  }
  
  state.qIdx = Math.max(0, Math.min(qs.length-1, state.qIdx+dir));
  if(state.qIdx===qs.length-1 && dir===1 && Object.keys(state.answers).filter(k=>k.startsWith(`${state.subject}-${state.diff}-`)).length===qs.length){
    const s = state.subject; const d = state.diff;
    const total = qs.length; const c = Object.values(state.answers).filter(a=>a.correct&&a===state.answers[`${s}-${d}-${Object.values(state.answers).indexOf(a)}`]).length;
    sendPrompt(`I just finished the ${LABELS[s]} quiz on ${d} difficulty. I got ${state.correct} correct and ${state.incorrect} incorrect, earning ${state.points} points total. Can you give me feedback on my performance and suggest topics to review?`);
    return;
  }
  render();
}

// Function to play music
function music_player(){
  // 
  let myAudio = document.getElementById('audio');
  myAudio.play();
}

render();


